### ISSUE TITLE
Use defaults from params.pp

### ISSUE THREAD

**Issue by seriv** [voxpupuli/puppet-smokeping#72]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.9
- Ruby: 2.1.9p490
- Distribution: opensource
- Module version: master

## How to reproduce (e.g Puppet code you use)
Try using module on RHEL-7 and you will not get daemon_user defined in params.pp as root, instead trying to use smokeping which does not exist.

## What are you seeing
"No such user smokeping" at attemt to chown in the puppet agent run.

## What behaviour did you expect instead
No errors.

## Output log
profile::smokeping::server, profile, server, role::network_management_server, role, network_management_server, node, netman.cs.umd.edu	change from root to smokeping failed: Could not find user smokeping

## Any additional information you'd like to impart
Module does not use inheritance, and defaults defined in params.pp never used in init.pp

**Comment by seriv** [comment]
https://github.com/voxpupuli/puppet-smokeping/pull/73 should fix it.

**Comment by kenyon** [comment]
Redid params handling in #138.
