### ISSUE TITLE
add support for Puppet 5

### ISSUE THREAD

**Issue by lesinigo** [voxpupuli/puppet-smokeping#82]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.x
- Ruby: all
- Distribution: all
- Module version: master branch as of today

## How to reproduce (e.g Puppet code you use)
Go on the forge, search for smokeping modules, check out compatibility

## What are you seeing
This module declares compatibility only with Puppet 4.7.x but < 5.0.0

## What behaviour did you expect instead
Compatibility with Puppet 5

## Any additional information you'd like to impart
I had not actually tested the module on Puppet 5, but will try to do that as time permits.

**Comment by alexjfisher** [comment]
@lesinigo The tests are actually run against puppet 5 and they pass.  It's probably fine for us to bump the version in the metadata.json.  If you do have the time for a quick test in your environment, please do then open a PR and we can get a new release out to the forge pretty quickly.
